# Generated by Django 2.0.3 on 2018-03-26 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='users.Companies'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='training_methods',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
